### ISSUE TITLE
Feature Request mcap2 Integration

### ISSUE THREAD

**Issue by JonasFrey96** [berndpfrommer/rosbag2_composable_recorder#4]
Hi Bernd, 

Thanks a lot for you great work.
Are you planning to also integrate mcap or do you know about a similar project allowing to write mcap bags directly.

Best regards, 
Jonas

**Comment by berndpfrommer** [comment]
Hi Jonas,

If you want to write the bag in mcap format, try just modifying [this line](https://github.com/berndpfrommer/rosbag2_composable_recorder/blob/9c6eb56538603b1403dc5a09f744a24c75e0b4c9/src/composable_recorder.cpp#L53).
But if you are running on Jazzy or Rolling you can use the new composable recorder node directly, i.e. you don't need the software in this repo anymore. And there you can set the output format with a ros parameter.

**Comment by JonasFrey96** [comment]
Hi Bernd, 

thanks a lot. This helps us out a lot.

Best regards,
Jonas
